env:
    CIRRUS_CLONE_DEPTH: 1
    token_telegram: "ENCRYPTED[15c3d8f17b8cea8a1f415ec21591db6c7a69fa669b7a4e8256209bf8a9b72816a892cc109b6fdb42f23c7c5f4a6328b4]"
    id_telegram: "ENCRYPTED[0df167bbed5acf79cc6bda2bdca11eb3f8cf4431222cc7c58520a070d6d5d27ae0a8cb2f62a450f5150aa356e0b14f4d]"
    rclone_config: "ENCRYPTED[5b989590dabfd448ff4b93021086808f6e187f957d5bd80a32a69005dfe1370f4fa0fa6e4e32dfdcc6e47e14eac188ea]"
    # credentials: "ENCRYPTED[a36b42522be46a7b58ceb973ce08b60006c0b8bd732373d4eedd4a04788a66d3d41427b44ae18a1bdb6d3273e4855d90]"

task:
    name: evox
    timeout_in: 120m
    container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 24G      

    mengunduh_ccache_background_script:
      - git config --global user.name "phoenix-1708"
      - git config --global user.email "harikumar1708@gmail.com"
      - git config --global color.ui true
      - sudo apt-get update -y
      - sudo apt-get upgrade -y
      - sudo apt-get install -y openjdk-11-jdk
      - sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
      - sudo apt-get install -y wget
      - sudo apt-get install -y jq
      #- git clone https://github.com/akhilnarang/scripts bscripts && cd bscripts && bash setup/android_build_env.sh && cd ..
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - df -h && free -h && nproc && cat /etc/os* && env
      - mkdir -p /tmp/ccache
      - rclone copy remote:ccache/ci2/ccache.tar.gz /tmp -P
      - cd /tmp
      - time tar xf ccache.tar.gz
      - ls /tmp
      - ls /tmp/ccache
      - rm -rf ccache.tar.gz
      - mkdir -p /tmp/rom
      - cd /tmp/rom
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -o compression=true
      - ccache -z
    chmod_script:
      - sudo chmod +x *
    memantau_background_script:
      - ./memantau
    mengsinkronisasi_script:
      - ./sinkronisasi
#    mengumpulkan_ccache_script:
#      - ./mengumpulkan_ccache
    membangun_akhir_script:
      - ./membangun_akhir
    mengunggah_script:
      - ./mengunggah
