#!/bin/bash

cd /tmp/rom

export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G
ccache -o compression=true
ccache -z

. build/envsetup.sh
lunch evolution_tissot-userdebug
mka evolution -j8
